# This is a hand-generated set of preterminal rules.
# It specifies a simple tag set which will be handled by the S2
# grammar and which can (though doesn't necessarily need to be)
# handled by the S1 grammar.
#
# The weights given here may be changed, but no new vocabulary
# items outside of allowed_words.txt should be added.

# Miscellaneous items that don't fit into any of our simple tags are
# given to Misc.  You will want to develop your own tags for these!

# Punctuations
1   Punc    .

# Singular and mass nouns.  Notice that only the
# ones that start with consonants get our Noun tag.
1    Noun    castle
1    Noun    king
1    Noun    defeater
1    Noun    sovereign
1    Noun    servant
1    Noun    corner
1    Noun    land
1    Noun    master
1    Noun    horse
1    Noun    sun
1    Noun    winter
1    Noun    coconut
1    Noun    pound
1    Noun    home
1    Noun    weight
1    Noun    story

# Determiners.
1    Det    a
1    Det    each
1    Det    no
1    Det    that
1    Det    the
1    Det    this

# Prepositions.
1    Prep    above
1    Prep    across
1    Prep    at
1    Prep    below
1    Prep    for
1    Prep    near
1    Prep    on
1    Prep    through
1    Prep    with

# Proper nouns.  Note that our Proper tag is just for people.
1    Proper    Arthur
1    Proper    _Sir _Lancelot
1    Proper    _Sir _Bedevere
1    Proper    Zoot
1    Proper    Patsy
1    _Sir      Sir
1    _Bedevere Bedevere
1    _Pendragon Pendragon
1    _Knight   Knight

# Verbs (third person singular present).
# Note that only transitive verbs get our VerbT tag,
# and some of those could also function as intransitives!
1    VerbT    has
1    VerbT    covers
1    VerbT    is
1    VerbT    drinks
1    VerbT    rides
# End-of-sentence.
1    Misc    .
1    Misc    ?
# Pauses.
1    Misc    ...
1    Misc    --
1    Misc    ;
1    Misc    :

# Coordinating conjunctions.
1    Misc    and
1    Misc    but
1    Misc    either
1    Misc    neither

# Numbers.
1    Misc    eight
1    Misc    five
1    Misc    one
1    Misc    5,000

# Expletive.
1    Misc    there

# Subordinating conjunctions.
1    Misc    that
1    Misc    so
1    Misc    while
1    Misc    because
1    Misc    if

# Modals.
1    Misc    can
1    Misc    could
1    Misc    might
1    Misc    ought
1    Misc    should
1    Misc    will
1    Misc    would


# Adjectives.
1    Misc    bloody
1    Misc    weary
1    Misc    unable
1    Misc    trusty
1    Misc    further
1    Misc    sacred
1    Misc    indigenous
1    Misc    hot
1    Misc    simple
1    Misc    hard    
1    Misc    comparable
1    Misc    yellow
1    Misc    plodding

# Comparative adjectives.
1    Misc    bloodier
1    Misc    wearier
1    Misc    hotter
1    Misc    tinier

# Superlative adjectives.
1    Misc    bloodiest
1    Misc    trustiest
1    Misc    simplest
1    Misc    hardest

# Plural nouns.
1    Misc    coconuts
1    Misc    halves
1    Misc    mountains
1    Misc    strangers
1    Misc    snakes
1    Misc    nights

# More proper nouns, not people.

1    Misc    Camelot
1    Misc    _Holy _Grail
1    _Grail  Grail
1    _Round  Round
1    _Table  Table

# Plural proper nouns.
1    Misc    Britons
1    Misc    Saxons

# Personal pronouns.
1    Misc    I
1    Misc    he
1    Misc    her
1    Misc    him
1    Misc    they


# Possessive personal pronouns
1    Misc    her
1    Misc    his
1    Misc    its
1    Misc    their

# Adverbs.
1    Misc    again
1    Misc    already
1    Misc    currently
1    Misc    frequently
1    Misc    precisely
1    Misc    successfully

# 'do'/'does'
1    Misc    do
1    Misc    does

# 'to'
1    Misc    to

# 'not'
1    Misc    not

# Verbs (base form).
1    Misc    have
1    Misc    speak
1    Misc    cover
1    Misc    be
1    Misc    drink
1    Misc    carry
1    Misc    migrate
1    Misc    know

# Verbs (past tense).
1    Misc    had
1    Misc    spoke
1    Misc    was
1    Misc    rode
1    Misc    grew
1    Misc    carried
1    Misc    suggested
1    Misc    migrated
1    Misc    knew

# Verbs (present participles).
1    Misc    having
1    Misc    speaking
1    Misc    being
1    Misc    drinking
1    Misc    carrying
1    Misc    migrating
1    Misc    knowing

# Verbs (past participle).
1    Misc    had
1    Misc    spoken
1    Misc    been
1    Misc    drunk
1    Misc    carried
1    Misc    migrated
1    Misc    known

# More third person singular verbs.
1    Misc    speaks
1    Misc    grows
1    Misc    migrates
1    Misc    knows

# Verbs (present, plural, third person).
1    Misc    have
1    Misc    speak
1    Misc    cover
1    Misc    ride
1    Misc    grow
1    Misc    suggest
1    Misc    know

# Wh-determiners.
1    Misc    that
1    Misc    what

# Wh-pronouns.
1    Misc    what
1    Misc    who

# Wh possessive pronoun.
1    Misc    whose

# Wh-adverbs
1    Misc    how
1    Misc    when
1    Misc    where

# Possessive marker.
1    Misc    's

# Some additional words from Monty Python
1    Misc    pull
1    Misc    other
1    Misc    you
1    Misc    you
1    Misc    fooling
1    Misc    happy
1    Misc    feel
1    Misc    happy
1    Misc    'm
1    Misc    thirty
1    Misc    seven
1    Misc    'm
1    Misc    old
1    Misc    're
1    Misc    yourself
1    Misc    're
1    Misc    in
1    Misc    we
1    Misc    an
1    Misc    commune
1    Misc    decisions
1    Misc    ratified
1    Misc    special
1    Misc    biweekly
1    Misc    meeting
1    Misc    order
1    Misc    you
1    Misc    quiet
1    Misc    well
1    Misc    'ow
1    Misc    did
1    Misc    you
1    Misc    become
1    Misc    then
1    Misc    am
1    Misc    your
1    Misc    mean
1    Misc    went
1    Misc    around
1    Misc    sayin'
1    Misc    an
1    Misc    emperor
1    Misc    just
1    Misc    some
1    Misc    moistened
1    Misc    bink
1    Misc    lobbed
1    Misc    scimitar
1    Misc    me
1    Misc    'd
1    Misc    put
1    Misc    me
1    Misc    away
1    Misc    now
1    Misc    we
1    Misc    see
1    Misc    violence
1    Misc    inherent
1    Misc    in
1    Misc    system
1    Misc    oh
1    Misc    come
1    Misc    see
1    Misc    violence
1    Misc    inherent
1    Misc    in
1    Misc    system
1    Misc    help
1    Misc    'm
1    Misc    repressed
1    Misc    peasant
1    Misc    you
1    Misc    fight
1    Misc    many
1    Misc    with
1    Misc    pass
1    Misc    move
1    Misc    man
1    Misc    come
1    Misc    you
1    Misc    pansy
1    Misc    victory
1    Misc    mine
1    Misc    you
1    Misc    going
1    Misc    bleed
1    Misc    me
1    Misc    you
1    Misc    're
1    Misc    loony
1    Misc    all
1    Misc    right
1    Misc    we
1    Misc    'll
1    Misc    call
1    Misc    draw
1    Misc    'll
1    Misc    bite
1    Misc    your
1    Misc    legs
1    Misc    off
1    Misc    we
1    Misc    found
1    Misc    witch
1    Misc    we
1    Misc    burn
1    Misc    'm
1    Misc    witch
1    Misc    well
1    Misc    second
1    Misc    thought
1    Misc    let
1    Misc    go
1    Misc    silly
1    Misc    place
1    Misc    King
1    Misc    your
1    Misc    purpose
1    Misc    Quest
1    Misc    go
1    Misc    tell
1    Misc    your
1    Misc    we
1    Misc    charged
1    Misc    God
1    Misc    blow
1    Misc    my
1    Misc    nose
1    Misc    you
1    Misc    so-called
1    Misc    Arthur-king
1    Misc    you
1    Misc    all
1    Misc    your
1    Misc    silly
1    Misc    English
1    Misc    knnnniggets
1    Misc    thppppt
1    Misc    strange
1    Misc    now
1    Misc    away
1    Misc    you
1    Misc    your
1    Misc    run
1    Misc    at
